name: deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3

      - run: node --version
      - run: npm --version

      - name: Install NPM Packages
        run: |
          npm install
      - name: Start SSG
        run: |
          npm run build
          touch ./build/.nojekyll
      - name: Deploy GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build